name: add-word

on:
  workflow_dispatch:
    inputs:
      word:
        description: A word
        required: true
        type: string

jobs:
  add-word:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up sd
        uses: kenji-miyake/setup-sd@v1

      - name: Update .cspell.json
        run: |
          sd -s \
            '"words": [' \
            '"words": [
              "${{ inputs.word }}",
            ' \
          .cspell.json

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: ${{ github.event.repository.default_branch }}
          branch: add-word-${{ inputs.word }}
          title: "feat(words): add ${{ inputs.word }}"
          commit-message: "feat(words): add ${{ inputs.word }}"
          body: "TODO: Update this comment and add some reference links."
          labels: |
            bot
            dependencies
          signoff: true
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Enable auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-operation == 'created' }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
