name: sort-cspell-json

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: verified

  sort-cspell-json:
    needs: prevent-no-label-execution
    if: ${{ github.event.pull_request.head.repo.owner.login == 'tier4' || needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install jq
        run: |
          sudo apt-get update && \
          sudo apt-get install -y jq

      - name: Run sort_cspell_json.sh
        run: |
          ./sort_cspell_json.sh

          # For backward compatibility
          cp .cspell.json cspell/.cspell.json

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Commit and push
        run: |
          if ! git diff --exit-code --quiet; then
            git add -u .
            git commit -m "chore: sort and uniq the words"
            git push
          fi
